// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/data/db/querier.go -destination=internal/service/mocks/mock_querier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	db "doit/internal/data/db"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// BulkUpdateTodoStatus mocks base method.
func (m *MockQuerier) BulkUpdateTodoStatus(ctx context.Context, arg db.BulkUpdateTodoStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateTodoStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateTodoStatus indicates an expected call of BulkUpdateTodoStatus.
func (mr *MockQuerierMockRecorder) BulkUpdateTodoStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateTodoStatus", reflect.TypeOf((*MockQuerier)(nil).BulkUpdateTodoStatus), ctx, arg)
}

// BulkUpdateUsersMetadata mocks base method.
func (m *MockQuerier) BulkUpdateUsersMetadata(ctx context.Context, arg db.BulkUpdateUsersMetadataParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateUsersMetadata", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateUsersMetadata indicates an expected call of BulkUpdateUsersMetadata.
func (mr *MockQuerierMockRecorder) BulkUpdateUsersMetadata(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateUsersMetadata", reflect.TypeOf((*MockQuerier)(nil).BulkUpdateUsersMetadata), ctx, arg)
}

// CleanupExpiredTokens mocks base method.
func (m *MockQuerier) CleanupExpiredTokens(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredTokens", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExpiredTokens indicates an expected call of CleanupExpiredTokens.
func (mr *MockQuerierMockRecorder) CleanupExpiredTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredTokens", reflect.TypeOf((*MockQuerier)(nil).CleanupExpiredTokens), ctx)
}

// CompleteTodo mocks base method.
func (m *MockQuerier) CompleteTodo(ctx context.Context, id uuid.UUID) (db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTodo", ctx, id)
	ret0, _ := ret[0].(db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteTodo indicates an expected call of CompleteTodo.
func (mr *MockQuerierMockRecorder) CompleteTodo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTodo", reflect.TypeOf((*MockQuerier)(nil).CompleteTodo), ctx, id)
}

// CountUserTodos mocks base method.
func (m *MockQuerier) CountUserTodos(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserTodos", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserTodos indicates an expected call of CountUserTodos.
func (mr *MockQuerierMockRecorder) CountUserTodos(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserTodos", reflect.TypeOf((*MockQuerier)(nil).CountUserTodos), ctx, userID)
}

// CountUserTodosByStatus mocks base method.
func (m *MockQuerier) CountUserTodosByStatus(ctx context.Context, arg db.CountUserTodosByStatusParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserTodosByStatus", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserTodosByStatus indicates an expected call of CountUserTodosByStatus.
func (mr *MockQuerierMockRecorder) CountUserTodosByStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserTodosByStatus", reflect.TypeOf((*MockQuerier)(nil).CountUserTodosByStatus), ctx, arg)
}

// CountUsers mocks base method.
func (m *MockQuerier) CountUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockQuerierMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockQuerier)(nil).CountUsers), ctx)
}

// CreateRefreshToken mocks base method.
func (m *MockQuerier) CreateRefreshToken(ctx context.Context, arg db.CreateRefreshTokenParams) (db.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, arg)
	ret0, _ := ret[0].(db.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockQuerierMockRecorder) CreateRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockQuerier)(nil).CreateRefreshToken), ctx, arg)
}

// CreateTodo mocks base method.
func (m *MockQuerier) CreateTodo(ctx context.Context, arg db.CreateTodoParams) (db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", ctx, arg)
	ret0, _ := ret[0].(db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockQuerierMockRecorder) CreateTodo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockQuerier)(nil).CreateTodo), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// GetOverdueTodos mocks base method.
func (m *MockQuerier) GetOverdueTodos(ctx context.Context, limit int32) ([]db.GetOverdueTodosRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverdueTodos", ctx, limit)
	ret0, _ := ret[0].([]db.GetOverdueTodosRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverdueTodos indicates an expected call of GetOverdueTodos.
func (mr *MockQuerierMockRecorder) GetOverdueTodos(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverdueTodos", reflect.TypeOf((*MockQuerier)(nil).GetOverdueTodos), ctx, limit)
}

// GetRefreshToken mocks base method.
func (m *MockQuerier) GetRefreshToken(ctx context.Context, tokenHash string) (db.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(db.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockQuerierMockRecorder) GetRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockQuerier)(nil).GetRefreshToken), ctx, tokenHash)
}

// GetRefreshTokenIncludingRevoked mocks base method.
func (m *MockQuerier) GetRefreshTokenIncludingRevoked(ctx context.Context, tokenHash string) (db.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenIncludingRevoked", ctx, tokenHash)
	ret0, _ := ret[0].(db.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenIncludingRevoked indicates an expected call of GetRefreshTokenIncludingRevoked.
func (mr *MockQuerierMockRecorder) GetRefreshTokenIncludingRevoked(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenIncludingRevoked", reflect.TypeOf((*MockQuerier)(nil).GetRefreshTokenIncludingRevoked), ctx, tokenHash)
}

// GetTodoByID mocks base method.
func (m *MockQuerier) GetTodoByID(ctx context.Context, id uuid.UUID) (db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodoByID", ctx, id)
	ret0, _ := ret[0].(db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodoByID indicates an expected call of GetTodoByID.
func (mr *MockQuerierMockRecorder) GetTodoByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodoByID", reflect.TypeOf((*MockQuerier)(nil).GetTodoByID), ctx, id)
}

// GetTodoByIDForUpdate mocks base method.
func (m *MockQuerier) GetTodoByIDForUpdate(ctx context.Context, id uuid.UUID) (db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodoByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodoByIDForUpdate indicates an expected call of GetTodoByIDForUpdate.
func (mr *MockQuerierMockRecorder) GetTodoByIDForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodoByIDForUpdate", reflect.TypeOf((*MockQuerier)(nil).GetTodoByIDForUpdate), ctx, id)
}

// GetTodoStats mocks base method.
func (m *MockQuerier) GetTodoStats(ctx context.Context, userID uuid.UUID) (db.GetTodoStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodoStats", ctx, userID)
	ret0, _ := ret[0].(db.GetTodoStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodoStats indicates an expected call of GetTodoStats.
func (mr *MockQuerierMockRecorder) GetTodoStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodoStats", reflect.TypeOf((*MockQuerier)(nil).GetTodoStats), ctx, userID)
}

// GetTodosByTags mocks base method.
func (m *MockQuerier) GetTodosByTags(ctx context.Context, arg db.GetTodosByTagsParams) ([]db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodosByTags", ctx, arg)
	ret0, _ := ret[0].([]db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodosByTags indicates an expected call of GetTodosByTags.
func (mr *MockQuerierMockRecorder) GetTodosByTags(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodosByTags", reflect.TypeOf((*MockQuerier)(nil).GetTodosByTags), ctx, arg)
}

// GetUserActiveRefreshTokens mocks base method.
func (m *MockQuerier) GetUserActiveRefreshTokens(ctx context.Context, userID uuid.UUID) ([]db.GetUserActiveRefreshTokensRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserActiveRefreshTokens", ctx, userID)
	ret0, _ := ret[0].([]db.GetUserActiveRefreshTokensRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserActiveRefreshTokens indicates an expected call of GetUserActiveRefreshTokens.
func (mr *MockQuerierMockRecorder) GetUserActiveRefreshTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserActiveRefreshTokens", reflect.TypeOf((*MockQuerier)(nil).GetUserActiveRefreshTokens), ctx, userID)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockQuerier) GetUserByID(ctx context.Context, id uuid.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockQuerierMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockQuerier)(nil).GetUserByID), ctx, id)
}

// GetUserByUsername mocks base method.
func (m *MockQuerier) GetUserByUsername(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockQuerierMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockQuerier)(nil).GetUserByUsername), ctx, username)
}

// GetUserTokenVersion mocks base method.
func (m *MockQuerier) GetUserTokenVersion(ctx context.Context, id uuid.UUID) (*int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTokenVersion", ctx, id)
	ret0, _ := ret[0].(*int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTokenVersion indicates an expected call of GetUserTokenVersion.
func (mr *MockQuerierMockRecorder) GetUserTokenVersion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTokenVersion", reflect.TypeOf((*MockQuerier)(nil).GetUserTokenVersion), ctx, id)
}

// HardDeleteTodo mocks base method.
func (m *MockQuerier) HardDeleteTodo(ctx context.Context, arg db.HardDeleteTodoParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDeleteTodo", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDeleteTodo indicates an expected call of HardDeleteTodo.
func (mr *MockQuerierMockRecorder) HardDeleteTodo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDeleteTodo", reflect.TypeOf((*MockQuerier)(nil).HardDeleteTodo), ctx, arg)
}

// HardDeleteTodos mocks base method.
func (m *MockQuerier) HardDeleteTodos(ctx context.Context, arg db.HardDeleteTodosParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDeleteTodos", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDeleteTodos indicates an expected call of HardDeleteTodos.
func (mr *MockQuerierMockRecorder) HardDeleteTodos(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDeleteTodos", reflect.TypeOf((*MockQuerier)(nil).HardDeleteTodos), ctx, arg)
}

// IncrementUserTokenVersion mocks base method.
func (m *MockQuerier) IncrementUserTokenVersion(ctx context.Context, id uuid.UUID) (*int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUserTokenVersion", ctx, id)
	ret0, _ := ret[0].(*int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementUserTokenVersion indicates an expected call of IncrementUserTokenVersion.
func (mr *MockQuerierMockRecorder) IncrementUserTokenVersion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUserTokenVersion", reflect.TypeOf((*MockQuerier)(nil).IncrementUserTokenVersion), ctx, id)
}

// ListTodosByUser mocks base method.
func (m *MockQuerier) ListTodosByUser(ctx context.Context, arg db.ListTodosByUserParams) ([]db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodosByUser", ctx, arg)
	ret0, _ := ret[0].([]db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTodosByUser indicates an expected call of ListTodosByUser.
func (mr *MockQuerierMockRecorder) ListTodosByUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodosByUser", reflect.TypeOf((*MockQuerier)(nil).ListTodosByUser), ctx, arg)
}

// ListTodosByUserAndStatus mocks base method.
func (m *MockQuerier) ListTodosByUserAndStatus(ctx context.Context, arg db.ListTodosByUserAndStatusParams) ([]db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodosByUserAndStatus", ctx, arg)
	ret0, _ := ret[0].([]db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTodosByUserAndStatus indicates an expected call of ListTodosByUserAndStatus.
func (mr *MockQuerierMockRecorder) ListTodosByUserAndStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodosByUserAndStatus", reflect.TypeOf((*MockQuerier)(nil).ListTodosByUserAndStatus), ctx, arg)
}

// ListUsers mocks base method.
func (m *MockQuerier) ListUsers(ctx context.Context, arg db.ListUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, arg)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockQuerierMockRecorder) ListUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockQuerier)(nil).ListUsers), ctx, arg)
}

// RevokeAllUserRefreshTokens mocks base method.
func (m *MockQuerier) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserRefreshTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserRefreshTokens indicates an expected call of RevokeAllUserRefreshTokens.
func (mr *MockQuerierMockRecorder) RevokeAllUserRefreshTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserRefreshTokens", reflect.TypeOf((*MockQuerier)(nil).RevokeAllUserRefreshTokens), ctx, userID)
}

// RevokeRefreshToken mocks base method.
func (m *MockQuerier) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockQuerierMockRecorder) RevokeRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockQuerier)(nil).RevokeRefreshToken), ctx, tokenHash)
}

// SearchTodosByTitle mocks base method.
func (m *MockQuerier) SearchTodosByTitle(ctx context.Context, arg db.SearchTodosByTitleParams) ([]db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTodosByTitle", ctx, arg)
	ret0, _ := ret[0].([]db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTodosByTitle indicates an expected call of SearchTodosByTitle.
func (mr *MockQuerierMockRecorder) SearchTodosByTitle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTodosByTitle", reflect.TypeOf((*MockQuerier)(nil).SearchTodosByTitle), ctx, arg)
}

// SearchUsersByEmail mocks base method.
func (m *MockQuerier) SearchUsersByEmail(ctx context.Context, arg db.SearchUsersByEmailParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersByEmail", ctx, arg)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByEmail indicates an expected call of SearchUsersByEmail.
func (mr *MockQuerierMockRecorder) SearchUsersByEmail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByEmail", reflect.TypeOf((*MockQuerier)(nil).SearchUsersByEmail), ctx, arg)
}

// UpdateRefreshTokenUsage mocks base method.
func (m *MockQuerier) UpdateRefreshTokenUsage(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshTokenUsage", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefreshTokenUsage indicates an expected call of UpdateRefreshTokenUsage.
func (mr *MockQuerierMockRecorder) UpdateRefreshTokenUsage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshTokenUsage", reflect.TypeOf((*MockQuerier)(nil).UpdateRefreshTokenUsage), ctx, id)
}

// UpdateTodo mocks base method.
func (m *MockQuerier) UpdateTodo(ctx context.Context, arg db.UpdateTodoParams) (db.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", ctx, arg)
	ret0, _ := ret[0].(db.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockQuerierMockRecorder) UpdateTodo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockQuerier)(nil).UpdateTodo), ctx, arg)
}

// UpdateUser mocks base method.
func (m *MockQuerier) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockQuerierMockRecorder) UpdateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockQuerier)(nil).UpdateUser), ctx, arg)
}

// UpdateUserLastLogin mocks base method.
func (m *MockQuerier) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLastLogin", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLastLogin indicates an expected call of UpdateUserLastLogin.
func (mr *MockQuerierMockRecorder) UpdateUserLastLogin(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLastLogin", reflect.TypeOf((*MockQuerier)(nil).UpdateUserLastLogin), ctx, id)
}

// UpdateUserPassword mocks base method.
func (m *MockQuerier) UpdateUserPassword(ctx context.Context, arg db.UpdateUserPasswordParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockQuerierMockRecorder) UpdateUserPassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockQuerier)(nil).UpdateUserPassword), ctx, arg)
}

// VerifyUserEmail mocks base method.
func (m *MockQuerier) VerifyUserEmail(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserEmail", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUserEmail indicates an expected call of VerifyUserEmail.
func (mr *MockQuerierMockRecorder) VerifyUserEmail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserEmail", reflect.TypeOf((*MockQuerier)(nil).VerifyUserEmail), ctx, id)
}
