# Grafana Datasource Configuration
# This tells Grafana where to get metrics from

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: Prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
