// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TodoPriority string

const (
	TodoPriorityLow    TodoPriority = "low"
	TodoPriorityMedium TodoPriority = "medium"
	TodoPriorityHigh   TodoPriority = "high"
	TodoPriorityUrgent TodoPriority = "urgent"
)

func (e *TodoPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodoPriority(s)
	case string:
		*e = TodoPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TodoPriority: %T", src)
	}
	return nil
}

type NullTodoPriority struct {
	TodoPriority TodoPriority `json:"todo_priority"`
	Valid        bool         `json:"valid"` // Valid is true if TodoPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodoPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TodoPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodoPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodoPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodoPriority), nil
}

type TodoStatus string

const (
	TodoStatusPending    TodoStatus = "pending"
	TodoStatusInProgress TodoStatus = "in_progress"
	TodoStatusCompleted  TodoStatus = "completed"
	TodoStatusArchived   TodoStatus = "archived"
)

func (e *TodoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodoStatus(s)
	case string:
		*e = TodoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TodoStatus: %T", src)
	}
	return nil
}

type NullTodoStatus struct {
	TodoStatus TodoStatus `json:"todo_status"`
	Valid      bool       `json:"valid"` // Valid is true if TodoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TodoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodoStatus), nil
}

type RefreshToken struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	UserID     uuid.UUID        `db:"user_id" json:"user_id"`
	TokenHash  string           `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	IsRevoked  bool             `db:"is_revoked" json:"is_revoked"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamp `db:"last_used_at" json:"last_used_at"`
	DeviceInfo json.RawMessage  `db:"device_info" json:"{{.Name}}"`
}

type Todo struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      TodoStatus         `db:"status" json:"status"`
	Priority    TodoPriority       `db:"priority" json:"priority"`
	Tags        []string           `db:"tags" json:"tags"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt   time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time          `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Email         string             `db:"email" json:"email"`
	Username      string             `db:"username" json:"username"`
	PasswordHash  string             `db:"password_hash" json:"password_hash"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at" json:"updated_at"`
	TokenVersion  *int32             `db:"token_version" json:"token_version"`
	Role          string             `db:"role" json:"role"`
}
