// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: todos.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateTodoStatus = `-- name: BulkUpdateTodoStatus :exec
UPDATE todos
SET status = $2
WHERE id = ANY($1::uuid [])
`

type BulkUpdateTodoStatusParams struct {
	Column1 []uuid.UUID `db:"column_1" json:"column_1"`
	Status  TodoStatus  `db:"status" json:"status"`
}

func (q *Queries) BulkUpdateTodoStatus(ctx context.Context, arg BulkUpdateTodoStatusParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateTodoStatus, arg.Column1, arg.Status)
	return err
}

const completeTodo = `-- name: CompleteTodo :one
UPDATE todos
SET status = 'completed',
    completed_at = NOW()
WHERE id = $1
    AND status != 'completed'
RETURNING id, user_id, title, description, status, priority, tags, metadata, due_date, completed_at, created_at, updated_at
`

func (q *Queries) CompleteTodo(ctx context.Context, id uuid.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, completeTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.Metadata,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUserTodos = `-- name: CountUserTodos :one
SELECT COUNT(*)
FROM todos
WHERE user_id = $1
`

func (q *Queries) CountUserTodos(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTodos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserTodosByStatus = `-- name: CountUserTodosByStatus :one
SELECT COUNT(*)
FROM todos
WHERE user_id = $1
    AND status = $2
`

type CountUserTodosByStatusParams struct {
	UserID uuid.UUID  `db:"user_id" json:"user_id"`
	Status TodoStatus `db:"status" json:"status"`
}

func (q *Queries) CountUserTodosByStatus(ctx context.Context, arg CountUserTodosByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTodosByStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
        id,
        user_id,
        title,
        description,
        status,
        priority,
        tags,
        metadata,
        due_date
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, title, description, status, priority, tags, metadata, due_date, completed_at, created_at, updated_at
`

type CreateTodoParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      TodoStatus         `db:"status" json:"status"`
	Priority    TodoPriority       `db:"priority" json:"priority"`
	Tags        []string           `db:"tags" json:"tags"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Tags,
		arg.Metadata,
		arg.DueDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.Metadata,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOverdueTodos = `-- name: GetOverdueTodos :many
SELECT t.id, t.user_id, t.title, t.description, t.status, t.priority, t.tags, t.metadata, t.due_date, t.completed_at, t.created_at, t.updated_at,
    u.email as user_email
FROM todos t
    JOIN users u ON t.user_id = u.id
WHERE t.due_date < NOW()
    AND t.status != 'completed'
ORDER BY t.due_date ASC
LIMIT $1
`

type GetOverdueTodosRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      TodoStatus         `db:"status" json:"status"`
	Priority    TodoPriority       `db:"priority" json:"priority"`
	Tags        []string           `db:"tags" json:"tags"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt   time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time          `db:"updated_at" json:"updated_at"`
	UserEmail   string             `db:"user_email" json:"user_email"`
}

func (q *Queries) GetOverdueTodos(ctx context.Context, limit int32) ([]GetOverdueTodosRow, error) {
	rows, err := q.db.Query(ctx, getOverdueTodos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverdueTodosRow{}
	for rows.Next() {
		var i GetOverdueTodosRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Tags,
			&i.Metadata,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, user_id, title, description, status, priority, tags, metadata, due_date, completed_at, created_at, updated_at
FROM todos
WHERE id = $1
`

func (q *Queries) GetTodoByID(ctx context.Context, id uuid.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.Metadata,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoByIDForUpdate = `-- name: GetTodoByIDForUpdate :one
SELECT id, user_id, title, description, status, priority, tags, metadata, due_date, completed_at, created_at, updated_at
FROM todos
WHERE id = $1 FOR
UPDATE
`

// Use FOR UPDATE to lock the row for updates (prevents race conditions)
func (q *Queries) GetTodoByIDForUpdate(ctx context.Context, id uuid.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByIDForUpdate, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.Metadata,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoStats = `-- name: GetTodoStats :one
SELECT COUNT(*) as total,
    COUNT(*) FILTER (
        WHERE status = 'pending'
    ) as pending,
    COUNT(*) FILTER (
        WHERE status = 'in_progress'
    ) as in_progress,
    COUNT(*) FILTER (
        WHERE status = 'completed'
    ) as completed,
    COUNT(*) FILTER (
        WHERE due_date < NOW()
            AND status != 'completed'
    ) as overdue
FROM todos
WHERE user_id = $1
`

type GetTodoStatsRow struct {
	Total      int64 `db:"total" json:"total"`
	Pending    int64 `db:"pending" json:"pending"`
	InProgress int64 `db:"in_progress" json:"in_progress"`
	Completed  int64 `db:"completed" json:"completed"`
	Overdue    int64 `db:"overdue" json:"overdue"`
}

func (q *Queries) GetTodoStats(ctx context.Context, userID uuid.UUID) (GetTodoStatsRow, error) {
	row := q.db.QueryRow(ctx, getTodoStats, userID)
	var i GetTodoStatsRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.InProgress,
		&i.Completed,
		&i.Overdue,
	)
	return i, err
}

const getTodosByTags = `-- name: GetTodosByTags :many
SELECT id, user_id, title, description, status, priority, tags, metadata, due_date, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1
    AND tags && $2::text []
ORDER BY created_at DESC
`

type GetTodosByTagsParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	Column2 []string  `db:"column_2" json:"column_2"`
}

func (q *Queries) GetTodosByTags(ctx context.Context, arg GetTodosByTagsParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodosByTags, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Tags,
			&i.Metadata,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteTodo = `-- name: HardDeleteTodo :exec
DELETE FROM todos
WHERE id = $1
    AND user_id = $2
`

type HardDeleteTodoParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) HardDeleteTodo(ctx context.Context, arg HardDeleteTodoParams) error {
	_, err := q.db.Exec(ctx, hardDeleteTodo, arg.ID, arg.UserID)
	return err
}

const hardDeleteTodos = `-- name: HardDeleteTodos :exec
DELETE FROM todos
WHERE id = ANY($1::uuid [])
    AND user_id = $2
`

type HardDeleteTodosParams struct {
	Column1 []uuid.UUID `db:"column_1" json:"column_1"`
	UserID  uuid.UUID   `db:"user_id" json:"user_id"`
}

func (q *Queries) HardDeleteTodos(ctx context.Context, arg HardDeleteTodosParams) error {
	_, err := q.db.Exec(ctx, hardDeleteTodos, arg.Column1, arg.UserID)
	return err
}

const listTodosByUser = `-- name: ListTodosByUser :many
SELECT id, user_id, title, description, status, priority, tags, metadata, due_date, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1
ORDER BY CASE
        priority
        WHEN 'urgent' THEN 1
        WHEN 'high' THEN 2
        WHEN 'medium' THEN 3
        WHEN 'low' THEN 4
    END,
    created_at DESC
LIMIT $2 OFFSET $3
`

type ListTodosByUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListTodosByUser(ctx context.Context, arg ListTodosByUserParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Tags,
			&i.Metadata,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByUserAndStatus = `-- name: ListTodosByUserAndStatus :many
SELECT id, user_id, title, description, status, priority, tags, metadata, due_date, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1
    AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTodosByUserAndStatusParams struct {
	UserID uuid.UUID  `db:"user_id" json:"user_id"`
	Status TodoStatus `db:"status" json:"status"`
	Limit  int32      `db:"limit" json:"limit"`
	Offset int32      `db:"offset" json:"offset"`
}

func (q *Queries) ListTodosByUserAndStatus(ctx context.Context, arg ListTodosByUserAndStatusParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByUserAndStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Tags,
			&i.Metadata,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodosByTitle = `-- name: SearchTodosByTitle :many
SELECT id, user_id, title, description, status, priority, tags, metadata, due_date, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1
    AND title ILIKE '%' || $2 || '%'
ORDER BY created_at DESC
LIMIT $3
`

type SearchTodosByTitleParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	Column2 *string   `db:"column_2" json:"column_2"`
	Limit   int32     `db:"limit" json:"limit"`
}

func (q *Queries) SearchTodosByTitle(ctx context.Context, arg SearchTodosByTitleParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, searchTodosByTitle, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Tags,
			&i.Metadata,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = COALESCE($1, title),
    description = COALESCE($2, description),
    status = COALESCE($3, status),
    priority = COALESCE($4, priority),
    tags = COALESCE($5, tags),
    metadata = COALESCE($6, metadata),
    due_date = COALESCE($7, due_date)
WHERE id = $8
RETURNING id, user_id, title, description, status, priority, tags, metadata, due_date, completed_at, created_at, updated_at
`

type UpdateTodoParams struct {
	Title       *string            `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      NullTodoStatus     `db:"status" json:"status"`
	Priority    NullTodoPriority   `db:"priority" json:"priority"`
	Tags        []string           `db:"tags" json:"tags"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	ID          uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Tags,
		arg.Metadata,
		arg.DueDate,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.Metadata,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
