// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredTokens = `-- name: CleanupExpiredTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) CleanupExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredTokens)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    id, user_id, token_hash, expires_at, device_info
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, token_hash, expires_at, is_revoked, created_at, last_used_at, device_info
`

type CreateRefreshTokenParams struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	UserID     uuid.UUID        `db:"user_id" json:"user_id"`
	TokenHash  string           `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	DeviceInfo json.RawMessage  `db:"device_info" json:"{{.Name}}"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.DeviceInfo,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, is_revoked, created_at, last_used_at, device_info FROM refresh_tokens
WHERE token_hash = $1 
  AND is_revoked = FALSE 
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const getRefreshTokenIncludingRevoked = `-- name: GetRefreshTokenIncludingRevoked :one
SELECT id, user_id, token_hash, expires_at, is_revoked, created_at, last_used_at, device_info FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

// For security checks (detect reuse)
func (q *Queries) GetRefreshTokenIncludingRevoked(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenIncludingRevoked, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const getUserActiveRefreshTokens = `-- name: GetUserActiveRefreshTokens :many
SELECT id, created_at, last_used_at, device_info
FROM refresh_tokens
WHERE user_id = $1 
  AND is_revoked = FALSE 
  AND expires_at > NOW()
ORDER BY last_used_at DESC
`

type GetUserActiveRefreshTokensRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamp `db:"last_used_at" json:"last_used_at"`
	DeviceInfo json.RawMessage  `db:"device_info" json:"{{.Name}}"`
}

func (q *Queries) GetUserActiveRefreshTokens(ctx context.Context, userID uuid.UUID) ([]GetUserActiveRefreshTokensRow, error) {
	rows, err := q.db.Query(ctx, getUserActiveRefreshTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserActiveRefreshTokensRow{}
	for rows.Next() {
		var i GetUserActiveRefreshTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.DeviceInfo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTokenVersion = `-- name: GetUserTokenVersion :one
SELECT token_version FROM users WHERE id = $1
`

func (q *Queries) GetUserTokenVersion(ctx context.Context, id uuid.UUID) (*int32, error) {
	row := q.db.QueryRow(ctx, getUserTokenVersion, id)
	var token_version *int32
	err := row.Scan(&token_version)
	return token_version, err
}

const incrementUserTokenVersion = `-- name: IncrementUserTokenVersion :one
UPDATE users 
SET token_version = token_version + 1
WHERE id = $1
RETURNING token_version
`

func (q *Queries) IncrementUserTokenVersion(ctx context.Context, id uuid.UUID) (*int32, error) {
	row := q.db.QueryRow(ctx, incrementUserTokenVersion, id)
	var token_version *int32
	err := row.Scan(&token_version)
	return token_version, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens 
SET is_revoked = TRUE
WHERE user_id = $1 AND is_revoked = FALSE
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens 
SET is_revoked = TRUE
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updateRefreshTokenUsage = `-- name: UpdateRefreshTokenUsage :exec
UPDATE refresh_tokens 
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateRefreshTokenUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenUsage, id)
	return err
}
