// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Lightweight endpoint that verifies the application process is alive and responsive. This endpoint does NOT check dependencies like database or Redis. Used by Kubernetes/container orchestrators as a liveness probe - if this fails repeatedly, the container will be restarted.\n\n**What it checks:**\n- Web server is responsive\n- Application hasn't crashed or deadlocked\n\n**What it does NOT check:**\n- Database connectivity\n- Redis/cache availability\n- External service availability\n\n**Response time target:** \u003c 10ms",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check endpoint (Liveness Probe)",
                "responses": {
                    "200": {
                        "description": "Application is alive and responsive",
                        "schema": {
                            "$ref": "#/definitions/api_v1_health_check.HealthResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Comprehensive health check that verifies all application dependencies are available and the application is ready to serve traffic. Used by Kubernetes/container orchestrators as a readiness probe - if this fails, the pod is removed from load balancer but NOT restarted.\n\n**What it checks:**\n- Database connectivity and responsiveness (PostgreSQL)\n- Redis/cache availability\n- Disk space availability\n\n**Behavior:**\n- Returns 200 OK when all checks pass\n- Returns 503 Service Unavailable when any check fails\n- Pod stays running but stops receiving traffic until checks pass again\n\n**Response time target:** \u003c 500ms",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check endpoint (Readiness Probe)",
                "responses": {
                    "200": {
                        "description": "Application is ready to receive traffic - all dependencies are healthy",
                        "schema": {
                            "$ref": "#/definitions/api_v1_health_check.ReadinessResponse"
                        }
                    },
                    "503": {
                        "description": "Application is not ready - one or more dependencies are unavailable",
                        "schema": {
                            "$ref": "#/definitions/api_v1_health_check.ReadinessResponse"
                        }
                    }
                }
            }
        },
        "/todos": {
            "post": {
                "description": "Create a new todo with the given title, description, priority, tags, metadata, and due date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Create a new todo",
                "parameters": [
                    {
                        "description": "Todo to create",
                        "name": "todo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_v1_todo.CreateTodoInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Todo created successfully",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_model.Todo"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_web.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_web.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_web.Error"
                        }
                    }
                }
            }
        },
        "/todos/{id}": {
            "get": {
                "description": "Get a todo by ID with the given ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todo"
                ],
                "summary": "Get a todo by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Todo retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_model.Todo"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_web.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_web.Error"
                        }
                    },
                    "404": {
                        "description": "Todo not found",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_web.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_web.Error"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "Authenticate user credentials and receive JWT access token and refresh token. The access token is short-lived (15 minutes) and used for API requests. The refresh token is long-lived (7 days) and used to obtain new access tokens.\nRate limit: 5 requests per minute per IP address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authenticate and login user",
                "parameters": [
                    {
                        "description": "User login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful with user info and tokens",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials (wrong email or password)",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "description": "Revoke the current refresh token, logging out the user from this specific device/session. Other active sessions remain valid.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout user (single device)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Refresh token to revoke",
                        "name": "X-Refresh-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Logged out successfully",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Missing refresh token header",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout/all": {
            "post": {
                "security": [
                    {
                        "bearer": []
                    }
                ],
                "description": "Revoke all refresh tokens for the authenticated user, logging them out from all devices and sessions. Use this when account security is compromised.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout user from all devices",
                "responses": {
                    "200": {
                        "description": "Logged out from all devices successfully",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.MessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access token",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/refresh": {
            "post": {
                "description": "Exchange a valid refresh token for a new access token and refresh token pair. This implements refresh token rotation for enhanced security - the old refresh token becomes invalid after use.\nSecurity: If an already-used refresh token is detected, all tokens for that user are revoked (possible token theft).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Refresh token from login response",
                        "name": "X-Refresh-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New token pair generated successfully",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.RefreshResponse"
                        }
                    },
                    "400": {
                        "description": "Missing refresh token header",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid, expired, or already-used refresh token",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "description": "Create a new user account with email, username, and password. Passwords must be at least 8 characters and should include uppercase, lowercase, numbers, and special characters. Email and username must be unique.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user account",
                "parameters": [
                    {
                        "description": "User registration information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully created user account",
                        "schema": {
                            "$ref": "#/definitions/doit_internal_model.User"
                        }
                    },
                    "400": {
                        "description": "Invalid input, duplicate email, or duplicate username",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api_v1_auth.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api_v1_auth.ErrorResponse": {
            "description": "Standard error response format",
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP status code",
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "description": "Error message describing what went wrong",
                    "type": "string",
                    "example": "validation error"
                },
                "fields": {
                    "description": "Field-specific validation errors (optional)",
                    "type": "object"
                }
            }
        },
        "api_v1_auth.LoginInput": {
            "description": "User login request payload",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "User's email address",
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "password": {
                    "description": "User's password",
                    "type": "string",
                    "example": "SecurePass123!"
                }
            }
        },
        "api_v1_auth.LoginResponse": {
            "description": "User login response with tokens",
            "type": "object",
            "properties": {
                "tokens": {
                    "$ref": "#/definitions/doit_internal_model.TokenPair"
                },
                "user": {
                    "type": "object"
                }
            }
        },
        "api_v1_auth.MessageResponse": {
            "description": "Simple message response (used for logout, delete, etc.)",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Response message",
                    "type": "string",
                    "example": "logged out successfully"
                }
            }
        },
        "api_v1_auth.RefreshResponse": {
            "description": "Response containing new access token",
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "New JWT access token",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "expires_in": {
                    "description": "Access token expiration time in seconds",
                    "type": "integer",
                    "example": 900
                },
                "refresh_token": {
                    "description": "New refresh token (rotation)",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "token_type": {
                    "description": "Token type (always \"Bearer\")",
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "api_v1_auth.RegisterInput": {
            "description": "User registration request payload",
            "type": "object",
            "required": [
                "confirm_password",
                "email",
                "password",
                "role",
                "username"
            ],
            "properties": {
                "confirm_password": {
                    "description": "Password confirmation (must match password field)",
                    "type": "string",
                    "example": "SecurePass123!"
                },
                "email": {
                    "description": "User's email address (must be unique)",
                    "type": "string",
                    "example": "jane.smith@example.com"
                },
                "password": {
                    "description": "Password (minimum 8 characters, should include uppercase, lowercase, numbers, and special characters)",
                    "type": "string",
                    "minLength": 8,
                    "example": "SecurePass123!"
                },
                "role": {
                    "description": "User role: user (default), admin, or moderator",
                    "type": "string",
                    "enum": [
                        "user",
                        "admin",
                        "moderator"
                    ],
                    "example": "user"
                },
                "username": {
                    "description": "Unique username (max 50 characters)",
                    "type": "string",
                    "maxLength": 50,
                    "example": "janesmith"
                }
            }
        },
        "api_v1_health_check.CheckResult": {
            "type": "object",
            "properties": {
                "latency": {
                    "description": "Latency indicates how long the check took to complete",
                    "type": "string",
                    "example": "15ms"
                },
                "message": {
                    "description": "Message provides additional context when a check fails",
                    "type": "string",
                    "example": "database unavailable: connection timeout"
                },
                "status": {
                    "description": "Status indicates if the check passed (\"ok\") or failed (\"failed\")",
                    "type": "string",
                    "enum": [
                        "ok",
                        "failed"
                    ],
                    "example": "ok"
                }
            }
        },
        "api_v1_health_check.HealthResponse": {
            "type": "object",
            "properties": {
                "stats": {
                    "description": "Stats contains optional runtime statistics",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api_v1_health_check.RuntimeStats"
                        }
                    ]
                },
                "status": {
                    "description": "Status indicates if the application is alive (always \"ok\" if responding)",
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "description": "Timestamp of the health check in RFC3339 format",
                    "type": "string",
                    "example": "2025-11-14T10:30:00Z"
                },
                "uptime": {
                    "description": "Uptime duration since application started",
                    "type": "string",
                    "example": "2h15m30s"
                },
                "version": {
                    "description": "Version of the application",
                    "type": "string",
                    "example": "v1.0.0"
                }
            }
        },
        "api_v1_health_check.ReadinessResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "description": "Checks contains the status of each dependency check",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/api_v1_health_check.CheckResult"
                    }
                },
                "status": {
                    "description": "Status indicates overall readiness (\"ready\" or \"not_ready\")",
                    "type": "string",
                    "enum": [
                        "ready",
                        "not_ready"
                    ],
                    "example": "ready"
                },
                "timestamp": {
                    "description": "Timestamp of the readiness check in RFC3339 format",
                    "type": "string",
                    "example": "2025-11-14T10:30:00Z"
                }
            }
        },
        "api_v1_health_check.RuntimeStats": {
            "type": "object",
            "properties": {
                "goroutines": {
                    "description": "Goroutines is the number of active goroutines",
                    "type": "integer",
                    "example": 42
                },
                "heap_objects": {
                    "description": "HeapObjects is the number of allocated heap objects",
                    "type": "integer",
                    "example": 250000
                },
                "memory_alloc_mb": {
                    "description": "MemoryAlloc is the allocated memory in megabytes",
                    "type": "integer",
                    "example": 128
                }
            }
        },
        "api_v1_todo.CreateTodoInput": {
            "type": "object"
        },
        "doit_internal_model.Todo": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "priority": {
                    "$ref": "#/definitions/doit_internal_model.TodoPriority"
                },
                "status": {
                    "$ref": "#/definitions/doit_internal_model.TodoStatus"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "doit_internal_model.TodoPriority": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high",
                "urgent"
            ],
            "x-enum-varnames": [
                "TodoPriorityLow",
                "TodoPriorityMedium",
                "TodoPriorityHigh",
                "TodoPriorityUrgent"
            ]
        },
        "doit_internal_model.TodoStatus": {
            "type": "string",
            "enum": [
                "pending",
                "in_progress",
                "completed",
                "archived"
            ],
            "x-enum-varnames": [
                "TodoStatusPending",
                "TodoStatusInProgress",
                "TodoStatusCompleted",
                "TodoStatusArchived"
            ]
        },
        "doit_internal_model.TokenPair": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "description": "seconds",
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "doit_internal_model.User": {
            "description": "User account information (password field is never included in responses)",
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Account creation timestamp",
                    "type": "string",
                    "example": "2025-11-08T10:00:00Z"
                },
                "email": {
                    "description": "User's email address",
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "email_verified": {
                    "description": "Whether the user's email has been verified",
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "description": "Unique user identifier (UUID v4)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "description": "Whether the user account is active",
                    "type": "boolean",
                    "example": true
                },
                "last_login_at": {
                    "description": "Last successful login timestamp",
                    "type": "string",
                    "example": "2025-11-08T10:30:00Z"
                },
                "metadata": {
                    "description": "Additional metadata (flexible key-value storage)",
                    "type": "object"
                },
                "role": {
                    "description": "User's role (user, admin, moderator)",
                    "enum": [
                        "user",
                        "admin",
                        "moderator"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/doit_internal_model.UserRole"
                        }
                    ],
                    "example": "user"
                },
                "token_version": {
                    "description": "Token version for refresh token rotation (used internally for security)",
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "description": "Last update timestamp",
                    "type": "string",
                    "example": "2025-11-08T10:00:00Z"
                },
                "username": {
                    "description": "User's unique username",
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "doit_internal_model.UserRole": {
            "type": "string",
            "enum": [
                "user",
                "admin",
                "moderator"
            ],
            "x-enum-comments": {
                "UserRoleAdmin": "Full system access",
                "UserRoleModerator": "Limited admin access",
                "UserRoleUser": "Regular user"
            },
            "x-enum-descriptions": [
                "Regular user",
                "Full system access",
                "Limited admin access"
            ],
            "x-enum-varnames": [
                "UserRoleUser",
                "UserRoleAdmin",
                "UserRoleModerator"
            ]
        },
        "doit_internal_web.Error": {
            "type": "object",
            "properties": {
                "err": {},
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
